spring:
  application:
    name: squeak-squeak

  profiles:
    include: secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
