spring:
  sql:
    init:
      data-locations: classpath:init.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  member-info-url: ${KAKAO_MEMBER_INFO_URL}
  access-token-url: ${KAKAO_ACCESS_TOKEN_URL}

naver:
  client-id: ${NAVER_CLIENT_ID}
  secret-id: ${NAVER_SECRET_ID}
  access-token-url: ${NAVER_ACCESS_TOKEN_URL}
  member-info-url: ${NAVER_MEMBER_INFO_URL}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  secret-id: ${GOOGLE_SECRET_ID}
  access-token-url: ${GOOGLE_ACCESS_TOKEN_URL}
  member-info-url: ${GOOGLE_MEMBER_INFO_URL}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

file: ${IMAGE_FILE}