spring:
  application:
    name: squeak-squeak

  profiles:
    group:
      "local": "local, common"
      "dev": "dev, common"
      "prod": "prod, common"
    active: local

---
spring:
  config:
    activate:
      on-profile: "local"

---
spring:
  config:
    activate:
      on-profile: "dev"

---
spring:
  config:
    activate:
      on-profile: "prod"
